"""Translate PF smoother CLI namespaces into runtime configuration."""

from __future__ import annotations

import argparse

from gnss_gpu.pf_smoother_config import PfSmootherConfig


def namespace_requests_epoch_diagnostics(args: argparse.Namespace) -> bool:
    return (
        args.epoch_diagnostics_out is not None
        or args.epoch_diagnostics_top_k > 0
        or args.smoother_tail_guard_ess_max_ratio is not None
        or args.smoother_tail_guard_dd_carrier_max_pairs is not None
        or args.smoother_tail_guard_dd_pseudorange_max_pairs is not None
        or args.smoother_tail_guard_min_shift_m is not None
        or args.smoother_tail_guard_expand_epochs is not None
        or args.smoother_tail_guard_expand_min_shift_m is not None
        or args.smoother_tail_guard_expand_dd_pseudorange_max_pairs is not None
        or args.smoother_widelane_forward_guard
        or str(args.fgo_local_window).strip().lower() == "auto"
    )


def namespace_to_run_kwargs(
    args: argparse.Namespace,
    *,
    position_update_sigma: float | None,
    use_smoother: bool,
) -> dict[str, object]:
    return {
        "n_particles": args.n_particles,
        "seed": args.seed,
        "sigma_pos": args.sigma_pos,
        "sigma_pr": args.sigma_pr,
        "position_update_sigma": position_update_sigma,
        "predict_guide": args.predict_guide,
        "use_smoother": use_smoother,
        "rover_source": args.urban_rover,
        "max_epochs": args.max_epochs,
        "skip_valid_epochs": args.skip_valid_epochs,
        "sigma_pos_tdcp": args.sigma_pos_tdcp,
        "sigma_pos_tdcp_tight": args.sigma_pos_tdcp_tight,
        "tdcp_tight_rms_max_m": args.tdcp_tight_rms_max,
        "resampling": "megopolis",
        "tdcp_elevation_weight": args.tdcp_elevation_weight,
        "tdcp_el_sin_floor": args.tdcp_el_sin_floor,
        "tdcp_rms_threshold": args.tdcp_rms_threshold,
        "residual_downweight": args.residual_downweight,
        "residual_threshold": args.residual_threshold,
        "pr_accel_downweight": args.pr_accel_downweight,
        "pr_accel_threshold": args.pr_accel_threshold,
        "use_gmm": args.gmm,
        "gmm_w_los": args.gmm_w_los,
        "gmm_mu_nlos": args.gmm_mu_nlos,
        "gmm_sigma_nlos": args.gmm_sigma_nlos,
        "doppler_position_update": args.doppler_position_update,
        "doppler_pu_sigma": args.doppler_pu_sigma,
        "doppler_per_particle": args.doppler_per_particle,
        "doppler_sigma_mps": args.doppler_sigma_mps,
        "doppler_velocity_update_gain": args.doppler_velocity_update_gain,
        "doppler_max_velocity_update_mps": args.doppler_max_velocity_update_mps,
        "doppler_min_sats": args.doppler_min_sats,
        "rbpf_velocity_kf": args.rbpf_velocity_kf,
        "rbpf_velocity_init_sigma": args.rbpf_velocity_init_sigma,
        "rbpf_velocity_process_noise": args.rbpf_velocity_process_noise,
        "rbpf_doppler_sigma": args.rbpf_doppler_sigma,
        "rbpf_velocity_kf_gate_min_dd_pairs": args.rbpf_velocity_kf_gate_min_dd_pairs,
        "rbpf_velocity_kf_gate_min_ess_ratio": args.rbpf_velocity_kf_gate_min_ess_ratio,
        "rbpf_velocity_kf_gate_max_spread_m": args.rbpf_velocity_kf_gate_max_spread_m,
        "pf_sigma_vel": args.pf_sigma_vel,
        "pf_velocity_guide_alpha": args.pf_velocity_guide_alpha,
        "pf_init_spread_vel": args.pf_init_spread_vel,
        "imu_tight_coupling": args.imu_tight_coupling,
        "imu_stop_sigma_pos": args.imu_stop_sigma_pos,
        "tdcp_position_update": args.tdcp_position_update,
        "tdcp_pu_sigma": args.tdcp_pu_sigma,
        "tdcp_pu_rms_max": args.tdcp_pu_rms_max,
        "tdcp_pu_spp_max_diff_mps": args.tdcp_pu_spp_max_diff_mps,
        "tdcp_pu_gate_dd_carrier_min_pairs": args.tdcp_pu_gate_dd_carrier_min_pairs,
        "tdcp_pu_gate_dd_carrier_max_pairs": args.tdcp_pu_gate_dd_carrier_max_pairs,
        "tdcp_pu_gate_dd_pseudorange_max_pairs": args.tdcp_pu_gate_dd_pseudorange_max_pairs,
        "tdcp_pu_gate_min_spread_m": args.tdcp_pu_gate_min_spread_m,
        "tdcp_pu_gate_max_spread_m": args.tdcp_pu_gate_max_spread_m,
        "tdcp_pu_gate_min_ess_ratio": args.tdcp_pu_gate_min_ess_ratio,
        "tdcp_pu_gate_max_ess_ratio": args.tdcp_pu_gate_max_ess_ratio,
        "tdcp_pu_gate_dd_pr_max_raw_median_m": args.tdcp_pu_gate_dd_pr_max_raw_median_m,
        "tdcp_pu_gate_dd_cp_max_raw_afv_median_cycles": args.tdcp_pu_gate_dd_cp_max_raw_afv_median_cycles,
        "tdcp_pu_gate_logic": args.tdcp_pu_gate_logic,
        "tdcp_pu_gate_stop_mode": args.tdcp_pu_gate_stop_mode,
        "mupf": args.mupf,
        "mupf_sigma_cycles": args.mupf_sigma_cycles,
        "mupf_snr_min": args.mupf_snr_min,
        "mupf_elev_min": args.mupf_elev_min,
        "dd_pseudorange": args.dd_pseudorange,
        "dd_pseudorange_sigma": args.dd_pseudorange_sigma,
        "dd_pseudorange_base_interp": args.dd_pseudorange_base_interp,
        "dd_pseudorange_gate_residual_m": args.dd_pseudorange_gate_residual_m,
        "dd_pseudorange_gate_adaptive_floor_m": args.dd_pseudorange_gate_adaptive_floor_m,
        "dd_pseudorange_gate_adaptive_mad_mult": args.dd_pseudorange_gate_adaptive_mad_mult,
        "dd_pseudorange_gate_epoch_median_m": args.dd_pseudorange_gate_epoch_median_m,
        "dd_pseudorange_gate_ess_min_scale": args.dd_pseudorange_gate_ess_min_scale,
        "dd_pseudorange_gate_ess_max_scale": args.dd_pseudorange_gate_ess_max_scale,
        "dd_pseudorange_gate_spread_min_scale": args.dd_pseudorange_gate_spread_min_scale,
        "dd_pseudorange_gate_spread_max_scale": args.dd_pseudorange_gate_spread_max_scale,
        "dd_pseudorange_gate_low_spread_m": args.dd_pseudorange_gate_low_spread_m,
        "dd_pseudorange_gate_high_spread_m": args.dd_pseudorange_gate_high_spread_m,
        "per_particle_nlos_gate": args.per_particle_nlos_gate,
        "per_particle_nlos_dd_pr_threshold_m": args.per_particle_nlos_dd_pr_threshold_m,
        "per_particle_nlos_dd_carrier_threshold_cycles": (
            args.per_particle_nlos_dd_carrier_threshold_cycles
        ),
        "per_particle_nlos_undiff_pr_threshold_m": args.per_particle_nlos_undiff_pr_threshold_m,
        "per_particle_huber": args.per_particle_huber,
        "per_particle_huber_dd_pr_k": args.per_particle_huber_dd_pr_k,
        "per_particle_huber_dd_carrier_k": args.per_particle_huber_dd_carrier_k,
        "per_particle_huber_undiff_pr_k": args.per_particle_huber_undiff_pr_k,
        "widelane": args.widelane,
        "widelane_min_fix_rate": args.widelane_min_fix_rate,
        "widelane_ratio_threshold": args.widelane_ratio_threshold,
        "widelane_dd_sigma": args.widelane_dd_sigma,
        "widelane_gate_min_fixed_pairs": args.widelane_gate_min_fixed_pairs,
        "widelane_gate_min_fix_rate": args.widelane_gate_min_fix_rate,
        "widelane_gate_min_spread_m": args.widelane_gate_min_spread_m,
        "widelane_gate_max_epoch_median_residual_m": args.widelane_gate_max_epoch_median_residual_m,
        "widelane_gate_max_pair_residual_m": args.widelane_gate_max_pair_residual_m,
        "smoother_skip_widelane_dd_pseudorange": args.smoother_skip_widelane_dd_pseudorange,
        "smoother_widelane_forward_guard": args.smoother_widelane_forward_guard,
        "smoother_widelane_forward_guard_min_shift_m": args.smoother_widelane_forward_guard_min_shift_m,
        "mupf_dd": args.mupf_dd,
        "mupf_dd_sigma_cycles": args.mupf_dd_sigma_cycles,
        "mupf_dd_base_interp": args.mupf_dd_base_interp,
        "mupf_dd_gate_afv_cycles": args.mupf_dd_gate_afv_cycles,
        "mupf_dd_gate_adaptive_floor_cycles": args.mupf_dd_gate_adaptive_floor_cycles,
        "mupf_dd_gate_adaptive_mad_mult": args.mupf_dd_gate_adaptive_mad_mult,
        "mupf_dd_gate_epoch_median_cycles": args.mupf_dd_gate_epoch_median_cycles,
        "mupf_dd_gate_low_ess_epoch_median_cycles": args.mupf_dd_gate_low_ess_epoch_median_cycles,
        "mupf_dd_gate_low_ess_max_ratio": args.mupf_dd_gate_low_ess_max_ratio,
        "mupf_dd_gate_low_ess_max_spread_m": args.mupf_dd_gate_low_ess_max_spread_m,
        "mupf_dd_gate_low_ess_require_no_dd_pr": args.mupf_dd_gate_low_ess_require_no_dd_pr,
        "mupf_dd_gate_ess_min_scale": args.mupf_dd_gate_ess_min_scale,
        "mupf_dd_gate_ess_max_scale": args.mupf_dd_gate_ess_max_scale,
        "mupf_dd_gate_spread_min_scale": args.mupf_dd_gate_spread_min_scale,
        "mupf_dd_gate_spread_max_scale": args.mupf_dd_gate_spread_max_scale,
        "mupf_dd_gate_low_spread_m": args.mupf_dd_gate_low_spread_m,
        "mupf_dd_gate_high_spread_m": args.mupf_dd_gate_high_spread_m,
        "mupf_dd_sigma_support_low_pairs": args.mupf_dd_sigma_support_low_pairs,
        "mupf_dd_sigma_support_high_pairs": args.mupf_dd_sigma_support_high_pairs,
        "mupf_dd_sigma_support_max_scale": args.mupf_dd_sigma_support_max_scale,
        "mupf_dd_sigma_afv_good_cycles": args.mupf_dd_sigma_afv_good_cycles,
        "mupf_dd_sigma_afv_bad_cycles": args.mupf_dd_sigma_afv_bad_cycles,
        "mupf_dd_sigma_afv_max_scale": args.mupf_dd_sigma_afv_max_scale,
        "mupf_dd_sigma_ess_low_ratio": args.mupf_dd_sigma_ess_low_ratio,
        "mupf_dd_sigma_ess_high_ratio": args.mupf_dd_sigma_ess_high_ratio,
        "mupf_dd_sigma_ess_max_scale": args.mupf_dd_sigma_ess_max_scale,
        "mupf_dd_sigma_max_scale": args.mupf_dd_sigma_max_scale,
        "carrier_anchor": args.carrier_anchor,
        "carrier_anchor_sigma_m": args.carrier_anchor_sigma_m,
        "carrier_anchor_min_sats": args.carrier_anchor_min_sats,
        "carrier_anchor_max_age_s": args.carrier_anchor_max_age_s,
        "carrier_anchor_max_residual_m": args.carrier_anchor_max_residual_m,
        "carrier_anchor_max_continuity_residual_m": args.carrier_anchor_max_continuity_residual_m,
        "carrier_anchor_min_stable_epochs": args.carrier_anchor_min_stable_epochs,
        "carrier_anchor_blend_alpha": args.carrier_anchor_blend_alpha,
        "carrier_anchor_reanchor_jump_cycles": args.carrier_anchor_reanchor_jump_cycles,
        "carrier_anchor_seed_dd_min_pairs": args.carrier_anchor_seed_dd_min_pairs,
        "mupf_dd_fallback_undiff": args.mupf_dd_fallback_undiff,
        "mupf_dd_fallback_sigma_cycles": args.mupf_dd_fallback_sigma_cycles,
        "mupf_dd_fallback_min_sats": args.mupf_dd_fallback_min_sats,
        "mupf_dd_fallback_prefer_tracked": args.mupf_dd_fallback_prefer_tracked,
        "mupf_dd_fallback_tracked_min_stable_epochs": args.mupf_dd_fallback_tracked_min_stable_epochs,
        "mupf_dd_fallback_tracked_min_sats": args.mupf_dd_fallback_tracked_min_sats,
        "mupf_dd_fallback_tracked_continuity_good_m": args.mupf_dd_fallback_tracked_continuity_good_m,
        "mupf_dd_fallback_tracked_continuity_bad_m": args.mupf_dd_fallback_tracked_continuity_bad_m,
        "mupf_dd_fallback_tracked_sigma_min_scale": args.mupf_dd_fallback_tracked_sigma_min_scale,
        "mupf_dd_fallback_tracked_sigma_max_scale": args.mupf_dd_fallback_tracked_sigma_max_scale,
        "mupf_dd_fallback_weak_dd_max_pairs": args.mupf_dd_fallback_weak_dd_max_pairs,
        "mupf_dd_fallback_weak_dd_max_ess_ratio": args.mupf_dd_fallback_weak_dd_max_ess_ratio,
        "mupf_dd_fallback_weak_dd_min_raw_afv_median_cycles": args.mupf_dd_fallback_weak_dd_min_raw_afv_median_cycles,
        "mupf_dd_fallback_weak_dd_require_no_dd_pr": args.mupf_dd_fallback_weak_dd_require_no_dd_pr,
        "mupf_dd_skip_low_support_ess_ratio": args.mupf_dd_skip_low_support_ess_ratio,
        "mupf_dd_skip_low_support_max_pairs": args.mupf_dd_skip_low_support_max_pairs,
        "mupf_dd_skip_low_support_max_spread_m": args.mupf_dd_skip_low_support_max_spread_m,
        "mupf_dd_skip_low_support_min_raw_afv_median_cycles": args.mupf_dd_skip_low_support_min_raw_afv_median_cycles,
        "mupf_dd_skip_low_support_require_no_dd_pr": args.mupf_dd_skip_low_support_require_no_dd_pr,
        "collect_epoch_diagnostics": namespace_requests_epoch_diagnostics(args),
        "smoother_position_update_sigma": args.smoother_position_update_sigma,
        "smoother_tail_guard_ess_max_ratio": args.smoother_tail_guard_ess_max_ratio,
        "smoother_tail_guard_dd_carrier_max_pairs": args.smoother_tail_guard_dd_carrier_max_pairs,
        "smoother_tail_guard_dd_pseudorange_max_pairs": args.smoother_tail_guard_dd_pseudorange_max_pairs,
        "smoother_tail_guard_min_shift_m": args.smoother_tail_guard_min_shift_m,
        "smoother_tail_guard_expand_epochs": args.smoother_tail_guard_expand_epochs,
        "smoother_tail_guard_expand_min_shift_m": args.smoother_tail_guard_expand_min_shift_m,
        "smoother_tail_guard_expand_dd_pseudorange_max_pairs": (
            args.smoother_tail_guard_expand_dd_pseudorange_max_pairs
        ),
        "stop_segment_constant": args.stop_segment_constant,
        "stop_segment_min_epochs": args.stop_segment_min_epochs,
        "stop_segment_source": args.stop_segment_source,
        "stop_segment_max_radius_m": args.stop_segment_max_radius_m,
        "stop_segment_blend": args.stop_segment_blend,
        "stop_segment_density_neighbors": args.stop_segment_density_neighbors,
        "stop_segment_static_gnss": args.stop_segment_static_gnss,
        "stop_segment_static_min_observations": (
            args.stop_segment_static_min_observations
        ),
        "stop_segment_static_prior_sigma_m": args.stop_segment_static_prior_sigma_m,
        "stop_segment_static_pr_sigma_m": args.stop_segment_static_pr_sigma_m,
        "stop_segment_static_dd_pr_sigma_m": args.stop_segment_static_dd_pr_sigma_m,
        "stop_segment_static_dd_cp_sigma_cycles": (
            args.stop_segment_static_dd_cp_sigma_cycles
        ),
        "stop_segment_static_max_update_m": args.stop_segment_static_max_update_m,
        "stop_segment_static_blend": args.stop_segment_static_blend,
        "fgo_local_window": args.fgo_local_window,
        "fgo_local_window_min_epochs": args.fgo_local_window_min_epochs,
        "fgo_local_dd_max_pairs": args.fgo_local_dd_max_pairs,
        "fgo_local_prior_sigma_m": args.fgo_local_prior_sigma_m,
        "fgo_local_motion_sigma_m": args.fgo_local_motion_sigma_m,
        "fgo_local_dd_huber_k": args.fgo_local_dd_huber_k,
        "fgo_local_pr_huber_k": args.fgo_local_pr_huber_k,
        "fgo_local_dd_sigma_cycles": args.fgo_local_dd_sigma_cycles,
        "fgo_local_pr_sigma_m": args.fgo_local_pr_sigma_m,
        "fgo_local_max_iterations": args.fgo_local_max_iterations,
        "fgo_local_lambda": args.fgo_local_lambda,
        "fgo_local_lambda_ratio_threshold": args.fgo_local_lambda_ratio_threshold,
        "fgo_local_lambda_sigma_cycles": args.fgo_local_lambda_sigma_cycles,
        "fgo_local_lambda_min_epochs": args.fgo_local_lambda_min_epochs,
        "fgo_local_motion_source": args.fgo_local_motion_source,
        "fgo_local_tdcp_rms_max_m": args.fgo_local_tdcp_rms_max_m,
        "fgo_local_tdcp_spp_max_diff_mps": args.fgo_local_tdcp_spp_max_diff_mps,
        "fgo_local_two_step": args.fgo_local_two_step,
        "fgo_local_stage1_prior_sigma_m": args.fgo_local_stage1_prior_sigma_m,
        "fgo_local_stage1_motion_sigma_m": args.fgo_local_stage1_motion_sigma_m,
        "fgo_local_stage1_pr_sigma_m": args.fgo_local_stage1_pr_sigma_m,
    }


def namespace_to_run_config(
    args: argparse.Namespace,
    *,
    position_update_sigma: float | None,
    use_smoother: bool,
) -> PfSmootherConfig:
    return PfSmootherConfig(
        **namespace_to_run_kwargs(
            args,
            position_update_sigma=position_update_sigma,
            use_smoother=use_smoother,
        )
    )
